# Generated by Django 5.1.3 on 2025-01-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20241031_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
