# Generated by Django 3.1.14 on 2024-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('South African', 'South African'), ('Others', 'Others')], max_length=45),
        ),
    ]
