# Generated by Django 5.1.1 on 2024-10-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_user'),
        ('teacher', '0003_timesheet'),
    ]

    operations = [
    ]
