# Generated by Django 5.1.3 on 2025-02-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_session_day'),
        ('teacher', '0008_timesheet_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'subject', 'teacher')},
        ),
    ]
