# Generated by Django 5.1.3 on 2025-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATPSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], max_length=20)),
                ('paper', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.TextField()),
                ('subject', models.CharField(default='Mathematics', max_length=50)),
                ('term', models.CharField(default='Term 1', max_length=10)),
            ],
        ),
    ]
