# Generated by Django 3.1.14 on 2024-08-20 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='name',
        ),
        migrations.AddField(
            model_name='designation',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_type',
            field=models.CharField(choices=[('Finance Manager', 'Finance Manager'), ('Centre Manager', 'Centre Manager'), ('Teacher', 'Teacher')], default='Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='designation',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='designation',
            name='email_address',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='name_surname',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='physical_address',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
