# Generated by Django 3.1.14 on 2024-08-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20240820_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='designation',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name_surname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='physical_address',
            field=models.TextField(default='No Address'),
        ),
    ]
