# Generated by Django 5.1.3 on 2024-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0011_auto_20241031_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='documents',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
