# Generated by Django 5.1.3 on 2025-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0014_alter_learner_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='disabilities',
            field=models.CharField(blank=True, choices=[('hearing_impairment', 'Hearing Impairment - Difficulties hearing properly (Needs to sit near/far)'), ('visual_impairment', 'Visual Impairment - Near/far sighted'), ('physical_disability', 'Physical Disability - Physically impaired'), ('cognitive_impairment', 'Cognitive Impairment')], max_length=50, null=True),
        ),
    ]
