# Generated by Django 3.1.14 on 2024-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20200128_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities'), ('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics')], max_length=15),
        ),
    ]
