# Generated by Django 4.2.16 on 2024-10-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_delete_center'),
        ('academic', '0005_delete_student'),
    ]

    operations = [
    ]
