# Generated by Django 5.1.3 on 2025-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_session_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='16:00'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00')], default='10:00'),
        ),
    ]
