# Generated by Django 5.1.3 on 2025-03-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3')], default='10', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Pathfinder ', 'Pathfinder Club'), ('Adventurer', 'Adventurer Club'), ('Master', 'Master Club')], default='Mathematics', max_length=21, unique=True),
        ),
    ]
