# Generated by Django 4.2.16 on 2024-10-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20241008_1721'),
        ('student', '0002_auto_20241009_0038'),
    ]

    operations = [
    ]
