# Generated by Django 3.1.14 on 2024-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20240825_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=514353, unique=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='status',
            field=models.CharField(choices=[('not enrolled', 'Not Enrolled'), ('enrolled', 'Enrolled'), ('regular', 'Regular'), ('irregular', 'Irregular'), ('passed', 'Passed')], default='not enrolled', max_length=15),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_certificate_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('South African', 'South African'), ('Zimbabwe', 'Zimbabwe')], max_length=45),
        ),
        migrations.AlterField(
            model_name='previousacademicinfo',
            name='board_roll',
            field=models.CharField(max_length=50),
        ),
    ]
