# Generated by Django 5.1.3 on 2025-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_manager', '0006_auto_20241031_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_manager',
        ),
        migrations.AddField(
            model_name='center',
            name='center_manager',
            field=models.ManyToManyField(related_name='center', to='center_manager.centermanager'),
        ),
    ]
