# Generated by Django 5.1.3 on 2025-01-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0013_learner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='documents',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
