# Generated by Django 5.1.3 on 2025-01-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_alter_learner_disabilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='birth_certificate_no',
            new_name='id_no',
        ),
    ]
