# Generated by Django 5.1.3 on 2025-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0016_rename_birth_certificate_no_learner_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='learner-documents/'),
        ),
    ]
