# Generated by Django 5.1.3 on 2025-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0017_learner_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='grade',
            field=models.CharField(choices=[('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
