# Generated by Django 5.1.3 on 2025-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0018_learner_grade_learner_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='document_file',
        ),
        migrations.AddField(
            model_name='learner',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='learner-documents/id-document/'),
        ),
        migrations.AddField(
            model_name='learner',
            name='previous_report',
            field=models.FileField(blank=True, null=True, upload_to='learner-documents/previous_report/'),
        ),
        migrations.AddField(
            model_name='learner',
            name='proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to='learner-documents/proof_of_residence/'),
        ),
    ]
