# Generated by Django 5.1.3 on 2025-03-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20241031_1608'),
        ('learner', '0019_remove_learner_document_file_learner_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='disabilities',
        ),
        migrations.AddField(
            model_name='learner',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='learner',
            name='allergy_medical_info',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='emergency_contanct_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='emergency_contanct_phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='parent_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='parent_phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='grade',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3')], max_length=2),
        ),
    ]
